apis/urls.py
from django.urls import path, include

urlpatterns = [
    path('v1/', include('apis.v1.urls')),
]

apps/expense_tracker/urls.py
from django.urls import path

app_name = 'expense_tracker'

from apps.expense_tracker.View import category, budget, expense, expenses_budget



urlpatterns = [
    ## For Category
    path('category-create/', category.CategoryCreateView.as_view(), name='category_create'),
    path('category-list/'  , category.CategoryListView.as_view(), name='category_list'),
    path('category-update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/', category.CategoryDeleteView.as_view(), name='category_delete'),


    ## For Budget
    path('budget-create/', budget.BudgetCreateView.as_view(), name='budget_create'),
    path('budget-list/'  , budget.BudgetListView.as_view(), name='budget_list'),
    path('budget-update/<int:pk>/', budget.BudgetUpdateView.as_view(), name='budget_update'),
    path('budget-delete/', budget.BudgetDeleteView.as_view(), name='budget_delete'),


    ## For Expenses
    path('expense-create/', expense.ExpenseCreateView.as_view(), name='expense_create'),
    path('expense-list/'  , expense.ExpenseListView.as_view(), name='expense_list'),
    path('expense-update/<int:pk>/', expense.ExpenseUpdateView.as_view(), name='expense_update'),
    path('expense-delete/', expense.ExpenseDeleteView.as_view(), name='expense_delete'),


    ## Expenses vs. Budget
    path('expense-vs-budget/'  , expenses_budget.ExpensesvsBudgetListView.as_view(), name='expense_vs_budget'),

    
]

apps/expense_tracker/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError

from django.contrib.auth import get_user_model
User = get_user_model()

## Custom 
from apps.core.models import TimestampedModel


from decimal import Decimal



# Create your models here.

"""
    #! Category Model
"""
class Category(TimestampedModel):
    owner = models.ForeignKey(
                User, 
                on_delete=models.CASCADE, 
                related_name="category", 
                verbose_name="Owner"
            ) 
    
    name = models.CharField(
            verbose_name="Budget Category Name",
            max_length=255,
            unique=True
        )

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ["name", "-created_at"]



"""
    #! Budget Model
"""
class Budget(TimestampedModel):
    owner = models.ForeignKey(
                User, 
                on_delete=models.CASCADE, 
                related_name="budgets", 
                verbose_name="Owner"
            ) 
    
    category = models.OneToOneField(
                Category, 
                on_delete=models.CASCADE, 
                verbose_name="Category"
            )

    amount = models.DecimalField(
                verbose_name="Amount",
                default=10,
                decimal_places=2,
                max_digits=10,
                validators=[MinValueValidator(Decimal("0.01"))],
            )

    def __str__(self):
        return f"{self.owner.get_full_name} - {self.category.name} - {self.amount}"
    
    @property       
    def total_expense(self):
        return self.category.expenses.aggregate(
                total=models.Sum('amount')
            )['total'] or Decimal('0.00')
    
    def total_expenses(self):
        return self.category.expenses.aggregate(
                total=models.Sum('amount')
            )['total'] or Decimal('0.00')
    
    def is_exceeded(self):
        return self.total_expenses() > self.amount
    
    class Meta:
        verbose_name = "Budget"
        verbose_name_plural = "Budgets"
        unique_together = ('owner', 'category')
        ordering = ["-created_at"]




"""
    #! Expense Model
"""
class Expense(TimestampedModel):
    owner = models.ForeignKey(
                User, 
                on_delete=models.CASCADE, 
                related_name="expenses", 
                verbose_name="Owner"
            ) 
    
    category = models.ForeignKey(
                Category,
                on_delete=models.CASCADE,
                related_name="expenses",
                verbose_name="Category"
            )

    amount = models.DecimalField(
                verbose_name="Amount",
                blank=False,
                default=10,
                decimal_places=2,
                max_digits=10,
                validators=[MinValueValidator(Decimal("0.01"))]
            )
    
    description = models.TextField(
                verbose_name="Description",
                null=True,
                blank=True
            )

    def __str__(self):
        return f"{self.owner.get_full_name} - {self.category.name} - {self.amount}"
    
    def clean(self):
        if self.amount <= 0:
            raise ValidationError("Expense amount must be greater than 0.")
        
    class Meta:
        verbose_name = "Expense"
        verbose_name_plural = "Expenses"
        ordering = ["-created_at"]



"""
    #! Alert Model
"""
class Alert(TimestampedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="alerts",
        verbose_name="User"
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="alerts",
        verbose_name="Category"
    )

    message = models.CharField(
        verbose_name="Alert Message",
        max_length=255
    )

    def __str__(self):
        return f"{self.user.get_full_name} - {self.category.name} - {self.message}"

    class Meta:
        verbose_name = "Alert"
        verbose_name_plural = "Alerts"
        ordering = ["-created_at"]

# You can create custom validators if necessary
def validate_budget_amount(value):
    if value < 0:
        raise ValidationError("Budget amount must be positive.")

def validate_expense_amount(value):
    if value <= 0:
        raise ValidationError("Expense amount must be greater than 0.")

apps/expense_tracker/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
User = get_user_model()

from django.forms import (
    ModelForm, TextInput, Select, CheckboxInput, NumberInput, FileInput, SelectMultiple, Textarea,
    PasswordInput, EmailInput
)

from django.contrib.auth.forms import ReadOnlyPasswordHashField

## Custom
from apps.expense_tracker.models import Category, Budget, Expense


"""
    Category Form
"""
class CategoryForm(forms.ModelForm):
    class Meta:
        model  = Category
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',  
                'placeholder': 'Enter Category Name',
                'required': True,
            }),
        }

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required': 'This field is required'}



"""
    Budget Form
"""
class BudgetForm(forms.ModelForm):
    class Meta:
        model  = Budget
        fields = ['category', 'amount']

        widgets = {
            'amount': forms.NumberInput(attrs={
                'class': 'form-control',  
                'placeholder': 'Enter amount',
                'required': True,
            }),

            'category' : Select(attrs={
                'class': 'form-select js-choice', 
            }),
        }

    # def __init__(self, *args, **kwargs):
    #     user = kwargs.pop('user', None)  ## Pop the user from kwargs
    #     super().__init__(*args, **kwargs)
    #     if user:
    #         used_categories = Budget.objects.filter(owner=user).values_list('category', flat=True)
    #         self.fields['category'].queryset = Category.objects.exclude(id__in=used_categories)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  ## Pop the user from kwargs
        instance = kwargs.get('instance', None)
        super().__init__(*args, **kwargs)

        if user:
            ## Exclude categories already used by the user except the current category
            if instance:
                used_categories = Budget.objects.filter(owner=user).exclude(id=instance.id).values_list('category', flat=True)
            else:
                used_categories = Budget.objects.filter(owner=user).values_list('category', flat=True)
                
            self.fields['category'].queryset = Category.objects.exclude(id__in=used_categories)



"""
    Expense Form
"""
class ExpenseForm(forms.ModelForm):
    class Meta:
        model  = Expense
        fields = ['category', 'amount', 'description']

        widgets = {
            'category' : Select(attrs={
                'class': 'form-select js-choice', 
            }),

            'amount': forms.NumberInput(attrs={
                'class': 'form-control',  
                'placeholder': 'Enter amount',
                'required': True,
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-control',  
                'placeholder': 'Write description',
                'rows' : 4,
                'cols' : 50
            }),

        }

apps/expense_tracker/templates/category/create.html
{% extends 'layouts/master.html' %}


{% block title %}
Category | Create
{% endblock title %}


{% block styles %}

{% endblock styles %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <form class="card mb-3" method="post">
            <div class="card-header">
                <div class="row flex-between-end">
                    <div class="col-auto align-self-center">
                        <h5 class="mb-0" data-anchor="data-anchor">
                            <i class="fa-brands fa-slack me-2 fs-1"></i>
                            Category Create
                        </h5>
                    </div>
                </div>
            </div>

            <div class="card-body bg-light">
                {% csrf_token %}

                <div class="form-group row mb-3">
                    <label class="col-md-3 col-form-label" for="old_password">Name</label>
                    <div class="col-md-8 position-relative">
                        {{form.name}}

                        {% if form.name.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in form.name.errors %}
                            <p class="fs--1">
                                <span class="fw-bold">Error:</span>
                                <span>{{ error }}</span>
                            </p>
                            {% endfor %}
                        </div>
                        {% endif %}

                    </div>
                </div>

            </div>


            <div class="form-group row">
                <div class="col-md-10 offset-md-3 card-footer">
                    <button type="submit" class="btn btn-primary ms-2 me-3">
                        <i class="fa fa-save me-2"></i>
                        Submit
                    </button>

                    <a href="{% url 'expense_tracker:category_list' %}" class="btn btn-secondary">
                        <i class="fa fa-times me-2"></i>
                        Cancel
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}


{% block js %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    var fieldErrors = {{ field_errors|safe }};

    $(document).ready(function () {
        if (fieldErrors.name.length > 0) {
            $('#id_name').addClass('is-invalid');
        }
    });
</script>
{% endblock js %}

apps/expense_tracker/templates/category/delete.html
<div class="modal fade" id="delete-{{category.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="toast show align-items-center" role="alert" data-bs-autohide="false" aria-live="assertive"
            aria-atomic="true">

            <form action="{% url 'expense_tracker:category_delete' %}" method="POST">
                {% csrf_token %}
                <div class="d-flex">
                    <div class="toast-body">Are you sure you want to delete this item?</div>
                    <button class="btn-close me-2 m-auto" type="button" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>

                <input type="hidden" name="category_id" value="{{category.id}}">

                <div class="mt-2 p-3 border-top">
                    <button class="btn btn-danger btn-sm" type="submit">
                        <span class="fas fa-trash me-1"></span>
                        Delete
                    </button>

                    <button class="btn btn-secondary btn-sm ms-2" type="button" data-bs-dismiss="modal">
                        <i class="fa-solid fa-xmark me-1"></i>
                        Close
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>

apps/expense_tracker/templates/category/list.html
{% extends 'layouts/master.html' %}

{% load static %}

{% block title %}
Expense | Category List
{% endblock title %}



{% block styles %}
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{% endblock styles %}




{% block content %}
<div class="card mb-3">

    <!-- Header Content -->
    <div class="card-header bg-light">
        <div class="row flex-between-center">

            <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">
                    <i class="fa-brands fa-slack fs-1 me-2"></i>Category List
                </h5>
            </div>

            <div class="col-8 col-sm-auto ms-auto text-end ps-0">
                <div class="d-flex flex-row" id="orders-actions">
                    <a href="{% url 'expense_tracker:category_create' %}" class="btn btn-konnect-default btn-sm" type="button">
                        <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
                        <span class="d-none d-sm-inline-block ms-1">New</span>
                    </a>
                    <!-- <button class="btn btn-konnect-default btn-sm mx-2" type="button" 
                        data-bs-toggle="modal" data-bs-target="#filter-modal">
                        <span class="fas fa-filter"></span>
                        <span class="d-none d-sm-inline-block ms-1">Filter</span>
                    </button>

                    <button class="btn btn-konnect-default btn-sm" type="button"
                        data-bs-toggle="modal" data-bs-target="#export-all-data">
                        <span class="fas fa-external-link-alt"></span>
                        <span class="d-none d-sm-inline-block ms-1">Export All</span>
                    </button> -->
                </div>
            </div>
        </div>
    </div>

    <!-- Body Content -->
    <div class="card-body p-4">
        <div class="table-responsive">

            <div class="d-flex justify-content-between mb-3">

                <!-- Delete Bulk User New Js(Sweet Alart) -->
                <div class="col-md-6">
                    <form method="post" id="delete_form">
                        {% csrf_token %}
                        <div class="d-none ms-3" id="bulk-select-actions">
                            <input type="hidden" name="delete_id_list" id="delete_id_list" value="">
                            <input type="hidden" name="delete_list">
                            <button class="btn btn-outline-danger me-1 mb-1" type="button"
                                onclick="handleDeleteButtonClick()">
                                <span class="fas fa-trash me-2 btn-icon"></span>
                                Delete
                                <span id="selected-count">(0) Selected</span>
                            </button>
                        </div>
                    </form>
                </div>

                <!-- Search -->
                <div class="col-md-3">
                    <form class="d-flex justify-content-between mb-3">
                        <div class="input-group">
                            <input class="form-control" type="search" name="search" placeholder="Search..."
                                aria-label="Search" value="{{ request.GET.search }}">
                            <button class="btn btn-outline-secondary" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>

            </div>

            <table width="100%" class="table table-bordered table-striped fs--1 mb-0">
                <thead class="bg-200 text-900">
                    <tr>
                        <th class="">
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox"
                                    data-bulk-select='{"body":"bulk-select-body","actions":"bulk-select-actions"}'
                                    onchange="handleBulkSelectChange(this)">
                                S/N
                            </div>
                        </th>
                        <th>Name</th>
                        <th class="text-center">Create At</th>
                        <th class="text-center">Update At</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody id="bulk-select-body">
                    {% for category in page_obj %}
                    <tr>
                        <td>
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" id="checkbox-{{category.id}}"
                                    data-bulk-select-row="data-bulk-select-row" onchange="handleCheckboxChange(this)"
                                    value="{{ category.id }}">
                                {{ page_obj.start_index|add:forloop.counter0 }}
                            </div>
                        </td>

                        <td>{{category.name}}</td>

                        <td class="text-center">
                            <span class="badge badge-soft-light fs--2">
                                {{ category.created_at|date:"D, d/M/Y" }}
                            </span><br>
                            <span class="badge badge-soft-light fs--2">
                                {{ category.created_at|date:"g:i A" }}
                            </span>
                        </td>

                        <td class="text-center">
                            <span class="badge badge-soft-light fs--2">
                                {{ category.updated_at|date:"D, d/M/Y" }}
                            </span><br>
                            <span class="badge badge-soft-light fs--2">
                                {{ category.updated_at|date:"g:i A" }}
                            </span>
                        </td>

                        <td>
                            <ul class="action text-center p-0 d-flex" style="flex-direction: column;">
                                <!-- <li>
                                    <a class="text-primary" href="">
                                        <span class="fas fa-eye text-primary"></span>
                                    </a>
                                </li> -->

                                <li>
                                    <a class="text-primary" href="{% url 'expense_tracker:category_update' category.id %}">
                                        <span class="fas fa-edit text-warning"></span>
                                    </a>
                                </li>

                                <li>
                                    <a class="text-danger cursor-pointer" data-bs-toggle="modal"
                                        data-bs-target="#delete-{{category.id}}">
                                        <span class="fas fa-trash text-danger"></span>
                                    </a>
                                </li>
                    
                                <div class="text-start">
                                    <!-- Delete Modal -->
                                    {% include 'category/delete.html' %}
                                </div>
                            </ul>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Pagination snd Counting -->
    {% include 'common/pagination.html' %}

</div>



<!-- Import Modal -->
{% include 'common/export_data.html' %}


{% endblock content %}




{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script>
    function updateSelectedCount() {
        const selectedCountSpan = document.getElementById('selected-count');
        const checkboxes = document.querySelectorAll('[data-bulk-select-row]');
        let selectedCount = 0;
        checkboxes.forEach(checkbox => {
            if (checkbox.checked) {
                selectedCount++;
            }
        });
        selectedCountSpan.textContent = `(${selectedCount}) Selected`;
    }

    function handleCheckboxChange(checkbox) {
        const deleteIdList = document.getElementById('delete_id_list');
        const bookingId = checkbox.value;

        if (checkbox.checked) {
            // Add the booking ID to the list if it's checked
            if (!deleteIdList.value.includes(bookingId)) {
                deleteIdList.value += (deleteIdList.value ? ',' : '') + bookingId;
            }
        } else {
            // Remove the booking ID from the list if it's unchecked
            deleteIdList.value = deleteIdList.value.split(',').filter(id => id !== bookingId).join(',');
        }

        updateSelectedCount(); // Update selected count after checkbox change
    }

    function handleBulkSelectChange(checkbox) {
        const checkboxes = document.querySelectorAll('[data-bulk-select-row]');
        checkboxes.forEach(checkbox => {
            checkbox.checked = checkbox.checked !== undefined ? checkbox.checked : false;
            handleCheckboxChange(checkbox);
        });
    }
</script>



<!-- Delete Bulk User Old Js(Js Confirm) -->
<!-- <script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete the selected item?");
    }

    function handleDeleteButtonClick() {
        if (confirmDelete()) {
            // Proceed with form submission if user confirms
            document.querySelector('form').submit();
        } else {
            // Cancel the deletion action if user cancels
            return false;
        }
    }
</script> -->


<!-- Delete Bulk User New Js(Sweet Alart) -->
<script>
    function handleDeleteButtonClick() {
        Swal.fire({
            title: "Are you sure!",
            text: "Do you want to delete the selected item?",
            showCancelButton: true,
            confirmButtonColor: "#203F99",
            cancelButtonColor : "#d33",
            cancelButtonText : "No",
            confirmButtonText: "Yes"
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('delete_form').submit();
            }
        });
    }
</script>
{% endblock js %}

apps/expense_tracker/templates/category/update.html
{% extends 'layouts/master.html' %}


{% block title %}
Category | Update
{% endblock title %}


{% block styles %}

{% endblock styles %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <form class="card mb-3" method="post">
            <div class="card-header">
                <div class="row flex-between-end">
                    <div class="col-auto align-self-center">
                        <h5 class="mb-0" data-anchor="data-anchor">
                            <i class="fa-brands fa-slack me-2 fs-1"></i>
                            Category Update
                        </h5>
                    </div>
                </div>
            </div>

            <div class="card-body bg-light">
                {% csrf_token %}

                <div class="form-group row mb-3">
                    <label class="col-md-3 col-form-label" for="old_password">Name</label>
                    <div class="col-md-8 position-relative">
                        {{form.name}}

                        {% if form.name.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in form.name.errors %}
                            <p class="fs--1">
                                <span class="fw-bold">Error:</span>
                                <span>{{ error }}</span>
                            </p>
                            {% endfor %}
                        </div>
                        {% endif %}

                    </div>
                </div>

            </div>


            <div class="form-group row">
                <div class="col-md-10 offset-md-3 card-footer">
                    <button type="submit" class="btn btn-primary ms-2 me-3">
                        <i class="fa fa-save me-2"></i>
                        Update
                    </button>

                    <a href="{% url 'expense_tracker:category_list' %}" class="btn btn-secondary">
                        <i class="fa fa-times me-2"></i>
                        Cancel
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}


{% block js %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    var fieldErrors = {{ field_errors| safe }};

    $(document).ready(function () {
        if (fieldErrors.name.length > 0) {
            $('#id_name').addClass('is-invalid');
        }
    });
</script>
{% endblock js %}